[package]
name = "saar"
version = "0.1.0"
edition = "2024"

[dependencies]
saar_core = { path = "../saar_core" }
saar_macro = { path = "../saar_macro" }
saar_components = { path = "../saar_components" }


