[package]
name = "stunt-router"
version = "0.1.0"
edition = "2024"

[dependencies]
stunt = { path = "../stunt", version = "0.1.0" }
stunt-router-macro = { path = "../stunt-router-macro", version = "0.1.0" }
web-sys = { version = "0.3.77", features = ["Document", "HtmlElement", "Element", "Node", "Window", "console", "Location"] }

