[package]
name = "puri_router"
version = "0.1.0"
edition = "2024"

[dependencies]
puri = { path = "../puri" }
web-sys = { version = "0.3.77", features = ["Document", "HtmlElement", "Element", "Node", "Window", "console", "Location"] }

