[package]
name = "saar_core"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = "0.10.0"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["Document", "HtmlElement", "Element", "Node", "Window", "console"] }


