[package]
name = "simple"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
puri = { path = "../../packages/puri" }
puri_router = { path = "../../packages/puri_router" }


