[package]
name = "puri"
version = "0.1.0"
edition = "2024"

[dependencies]
puri_macro = { path = "../puri_macro" }
spin = "0.10.0"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["Document", "HtmlElement", "Element", "Node", "Text", "Window", "console"] }
itertools = "0.14.0"


